name: Docker build and push
on:
  push:

jobs:
  build:
    name: docker build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set IMAGE_TAG
        run: |
          IMAGE_TAG=$(curl -fsL https://raw.githubusercontent.com/l3tnun/EPGStation/master/package-lock.json | jq .version -r)
          echo "::set-env name=IMAGE_TAG::$IMAGE_TAG"
      - name: Build image
        run: |
          docker build . -t yasuoza/epgstation:$IMAGE_TAG
      - name: Login to Docker Hub
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_PASS: ${{ secrets.DOCKER_HUB_PASS }}
        run: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
      - name: Push Docker Hub
        run: |
          docker push yasuoza/epgstation:$IMAGE_TAG
