name: PR Docker build and push
on:
  pull_request_target:

jobs:
  build:
    name: PR docker build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install buildx
        if: steps.check_remote_image_tag.outputs.remote_tag_exists != 'true'
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ github.ref }}-${{ github.sha }}
            ${{ github.ref }}
            refs/head/master

      - name: Set IMAGE_TAG
        run: |
          IMAGE_TAG=$(cat Dockerfile | awk '/FROM/{print $2}' | awk -F':v' '{print $2}')
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Push Docker Hub
        if: steps.check_remote_image_tag.outputs.remote_tag_exists != 'true'
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: |
            yasuoza/epgstation:latest
            yasuoza/epgstation:${{ env.IMAGE_TAG }}
          build-args: |
            IMAGE_TAG=${{ env.IMAGE_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
